-- insert 
--    into
--        person(name,surname,login,password,role,age)
--       
--    values
--        ('admin_name','admin_surname','admin','admin','ROLE_ADMIN',99);
--        
--  insert 
--    into
--        person(name,surname,login,password,role,age)
--       
--    values
--        ('user','user','user','user','ROLE_USER',99);
--        
--  insert 
--    into
--        person(name,surname,login,password,role,age)
--       
--    values
--        ('dwa','adwad','daw','','ROLE_USER',99);
--        
